/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.theluckyseven.frantic;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class GameSetupTest {
    @Test void appHasAGreeting() {
        GameSetup classUnderTest = new GameSetup();
        assertNotNull(classUnderTest.getGreeting(), "Main should have a greeting");
    }
}
